config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # A user can see all the lists
  # get 'lists', to: 'lists#index'

  # # A user can create a new list
  # get 'lists/new', to: 'lists#new', as: :new_list
  # post 'lists', to: "lists#create"

  # # A user can see the details of a given list and its name
  # get 'lists/:id', to: 'lists#show', as: :list

  root to: "lists#index"
  resources :lists, only: %i[index create show new]
  # resources :movies, only: [ :index, :show ]



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_list
    @list = List.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>My Lists</h1>
  <ul>
  <% @lists.each do |list| %>
    <li>
    <%= list.id %>
    <%= link_to "#{list.name}", list %>
    </li>
  <% end %>
  </ul>

  <%= link_to 'Add a list', new_list_path %> |
</div>

app/views/lists/new.html.erb
<%# <form action="/restaurants/234/reviews"></form> %>
<div class="container">
  <h1>New List</h1>
  <%= simple_form_for([@list]) do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
  <% end %>
  <%= link_to 'Back', lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1>My List</h1>
  <%= "#{@list.id} - #{@list.name}" %>
  <br><br><br>
  <%= link_to 'Back', lists_path %>

</div>